---
title: "Our World in Data: Key Crop Yields"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{key_crop_yields}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cwdata)
library(dplyr)
library(ggplot2)
```

```{r}
key_crop_yields %>% 
  distinct(year)
```

```{r}
key_crop_yields %>% 
  filter(year == 2017) %>% 
  group_by(crop) %>% 
  summarise(tonnes_per_hectare = sum(tonnes_per_hectare,na.rm = TRUE)) %>% 
  ggplot(aes(x = forcats::fct_reorder(crop,tonnes_per_hectare,.desc = TRUE),
                      y = tonnes_per_hectare))+
    geom_col()+
  theme_bw()+
  labs(title = "Global crop production",
       x = "Crop",
       y = "Tonnes per hectare"
  )
```

The most produced crop in the world is potatoes in 2017. Has this always been the case?

```{r}
key_crop_yields %>% 
  group_by(year,crop) %>% 
  summarise(tonnes_per_hectare = sum(tonnes_per_hectare,na.rm = TRUE)) %>% 
  ggplot2::ggplot(aes(x = year,
                      y = tonnes_per_hectare,
                      colour = crop))+
    geom_line()+
  theme_bw()+
  labs(title = "Global crop production",
       x = "Crop",
       y = "Tonnes per hectare"
  )
```


Looks like potatoes have always been widely grown, but before 1977 bananas took the top spot!
